[tasks.build]
command = "cargo"
args = ["build", "--release"]


[tasks.cargo_install]
command = "cargo"
args = ["install", "--path", "."]

[tasks.generate_shell_completions]
command = "alchemist"
args = ["shell-complete"]

[tasks.install]
serial_tasks = ["cargo_install", "generate_shell_completions"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.reinstall]
serial_tasks = ["clean", "install"]

[tasks.rebuild]
serial_tasks = ["clean", "build"]
